CREATE TABLE
    IF NOT EXISTS employees (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        user_id INT UNIQUE NULL,
        school_id INT NOT NULL,
        employee_code VARCHAR(30) UNIQUE NOT NULL,
        first_name VARCHAR(100) NOT NULL,
        -- middle_name VARCHAR(100),
        last_name VARCHAR(100),
        email VARCHAR(150) UNIQUE,
        mobile VARCHAR(20) UNIQUE NOT NULL,
        gender ENUM ('male', 'female', 'other'),
        dob DATE,
        blood_group VARCHAR(10),
        aadhaar_no VARCHAR(20),
        joining_date DATE NOT NULL,
        designation VARCHAR(100) NOT NULL,
        department VARCHAR(100),
        qualification VARCHAR(255),
        experience_years DECIMAL(4, 1),
        salary DECIMAL(12, 2),
        -- Address
        current_area VARCHAR(100),
        current_city VARCHAR(100),
        current_district VARCHAR(100),
        current_state VARCHAR(100),
        current_postal_code VARCHAR(20),
        current_address TEXT,
        current_address_same_as_permanent BOOLEAN DEFAULT FALSE,
        permanent_address TEXT,
        permanent_area VARCHAR(100),
        permanent_city VARCHAR(100),
        permanent_district VARCHAR(100),
        permanent_state VARCHAR(100),
        permanent_postal_code VARCHAR(20),
        -- Emergency
        emergency_contact VARCHAR(20),
        emergency_relationship ENUM (
            'wife',
            'husband',
            'son',
            'daughter',
            'friend',
            'relative',
            'father',
            'mother',
            'other'
        ),
        -- Bank Details
        bank_name VARCHAR(255),
        branch_name VARCHAR(255),
        account_number VARCHAR(20),
        account_type VARCHAR(100),
        ifsc_code VARCHAR(15),
        -- Documents
        photo_url VARCHAR(500),
        aadhaar_card_url VARCHAR(500),
        pan_card_url VARCHAR(500),
        passport_size_photo_url VARCHAR(500),
        degree_certificate_url VARCHAR(500),
        experience_certificate_url VARCHAR(500),
        signature_url VARCHAR(500),
        status ENUM ('active', 'inactive', 'resigned', 'terminated') DEFAULT 'active',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE CASCADE,
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
    );