-- CREATE TABLE
--     IF NOT EXISTS employee_payroll (
--         id BIGINT AUTO_INCREMENT PRIMARY KEY,
--         employee_id BIGINT NOT NULL,
--         salary_year INT,
--         salary_month INT,
--         total_working_days INT,
--         present_days DECIMAL(5, 2),
--         absent_days DECIMAL(5, 2),
--         leave_days DECIMAL(5, 2),
--         overtime_hours DECIMAL(6, 2),
--         gross_salary DECIMAL(12, 2),
--         total_deductions DECIMAL(12, 2),
--         net_salary DECIMAL(12, 2),
--         payroll_status ENUM ('draft', 'processed', 'paid') DEFAULT 'draft',
--         processed_at DATETIME,
--         UNIQUE KEY uq_payroll (employee_id, salary_year, salary_month),
--         FOREIGN KEY (employee_id) REFERENCES employees (id)
--     );
CREATE TABLE
    IF NOT EXISTS employee_payroll (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        school_id INT NOT NULL,
        employee_id BIGINT NOT NULL,
        salary_structure_id BIGINT NOT NULL,
        payroll_year YEAR NOT NULL,
        payroll_month TINYINT NOT NULL,
        total_working_days INT NOT NULL,
        present_days DECIMAL(5, 2) DEFAULT 0,
        absent_days DECIMAL(5, 2) DEFAULT 0,
        paid_leave_days DECIMAL(5, 2) DEFAULT 0,
        unpaid_leave_days DECIMAL(5, 2) DEFAULT 0,
        half_days DECIMAL(5, 2) DEFAULT 0,
        overtime_hours DECIMAL(6, 2) DEFAULT 0,
        gross_salary DECIMAL(12, 2) NOT NULL,
        overtime_amount DECIMAL(12, 2) DEFAULT 0,
        bonus DECIMAL(12, 2) DEFAULT 0,
        incentive DECIMAL(12, 2) DEFAULT 0,
        total_allowances DECIMAL(12, 2) DEFAULT 0,
        pf DECIMAL(12, 2) DEFAULT 0,
        esi DECIMAL(12, 2) DEFAULT 0,
        professional_tax DECIMAL(12, 2) DEFAULT 0,
        income_tax DECIMAL(12, 2) DEFAULT 0,
        loan_deduction DECIMAL(12, 2) DEFAULT 0,
        other_deductions DECIMAL(12, 2) DEFAULT 0,
        total_deductions DECIMAL(12, 2) DEFAULT 0,
        net_salary DECIMAL(12, 2) NOT NULL,
        payment_status ENUM ('draft', 'processed', 'paid', 'cancelled') DEFAULT 'draft',
        payment_date DATE NULL,
        payment_method ENUM ('cash', 'bank_transfer', 'upi', 'cheque') NULL,
        transaction_reference VARCHAR(255),
        remarks TEXT,
        generated_by BIGINT,
        generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE KEY uq_payroll (employee_id, payroll_year, payroll_month),
        FOREIGN KEY (school_id) REFERENCES schools (id),
        FOREIGN KEY (employee_id) REFERENCES employees (id),
        FOREIGN KEY (salary_structure_id) REFERENCES employee_salary_structures (id),
        FOREIGN KEY (generated_by) REFERENCES employees (id)
    );